name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: JVM - Test and publish a snapshot
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.3.5, 2.13.16, 2.12.20, 2.11.12]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    env:
      HAS_SECRETS: ${{ secrets.SONATYPE_PASSWORD != '' }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v4-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Runs tests
        run: sbt -jvm-opts ci/ci.jvmopts ++${{ matrix.scala }} test

      - name: Publish a snapshot ${{ github.ref }}
        if: env.HAS_SECRETS == 'true'
        run: sbt ++${{ matrix.scala }} coreJVM/publish
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  buildJs:
    name: JS - Test and publish a snapshot
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.3.5, 2.13.16, 2.12.20]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    env:
      HAS_SECRETS: ${{ secrets.SONATYPE_PASSWORD != '' }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v4-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Runs tests
        run: sbt -jvm-opts ci/ci.jvmopts ++${{ matrix.scala }} coreJS/test

      - name: Publish a snapshot ${{ github.ref }}
        if: env.HAS_SECRETS == 'true'
        run: sbt ++${{ matrix.scala }} coreJS/publish
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

